import pandas as pd

df = pd.read_csv('../data/Spotify-2000.csv')

genre_map = {
    "acid jazz":        "Jazz",
"acoustic pop":        "Pop",
"adult standards":        "Pop",
"afropop":        "Rap/Hip-Hop",
"alaska indie":        "Rock",
"album rock":        "Rock",
"alternative country":      "Folk/Country"  ,
"alternative dance":        "House/Electronic/Trance",
"alternative hip hop":       "Rap/Hip-Hop" ,
"alternative metal":        "Hard Rock/Metal",
"alternative pop":        "Pop",
"alternative pop rock":       "Pop" ,
"alternative rock":        "Rock",
"arkansas country":        "Folk/Country",
"art pop":        "Pop",
"art rock":        "Rock",
"atl hip hop":        "Rap/Hip-Hop",
"australian alternative rock": "Rock"       ,
"australian americana":        "Folk/Country",
"australian dance":       "House/Electronic/Trance" ,
"australian indie folk":      "Folk/Country"  ,
"australian pop":       "Pop" ,
"australian psych":       "Hard Rock/Metal" ,
"australian rock":        "Rock",
"austropop":        "Pop",
"barbadian pop":        "Pop",
"baroque pop":        "Pop",
"basshall":       "House/Electronic/Trance" ,
"bebop":       "Jazz" ,
"belgian pop":       "Pop" ,
"belgian rock":        "Rock",
"big beat":        "House/Electronic/Trance",
"big room":       "House/Electronic/Trance" ,
"blues":       "Jazz" ,
"blues rock":      "Rock"  ,
"bow pop":       "Pop" ,
"boy band":        "Pop",
"brill building pop":       "Pop" ,
"british alternative rock":     "Rock"   ,
"british folk":        "Folk/Country",
"british invasion":        "Rock & Roll",
"british singer-songwriter":        "Folk/Country",
"british soul":        "Soul/Funk",
"britpop":       "Pop",
"bubblegum pop":        "Pop",
"canadian folk":        "Folk/Country",
"canadian pop":        "Pop",
"canadian rock":        "Rock",
"candy pop":        "Pop",
"carnaval limburg":       "Folk/Country" ,
"ccm":        "Rock",
"celtic":        "Other",
"celtic punk":       "Punk" ,
"celtic rock":        "Rock",
"chamber pop":        "Pop",
"chanson":        "Folk/Country",
"chicago soul":        "Soul/Funk",
"christelijk":        "Other",
"classic canadian rock":     "Rock"   ,
"classic country pop":        "Pop",
"classic italian pop":        "Pop",
"classic rock":        "Rock",
"classic schlager":      "Pop"  ,
"classic soul":       "Soul/Funk" ,
"classic soundtrack":      "Other"  ,
"classic uk pop":        "Pop",
"classical rock":        "Rock",
"compositional ambient":      "Other"  ,
"contemporary country":        "Folk/Country",
"contemporary vocal jazz":        "Jazz",
"cyberpunk":        "Punk",
"dance pop":        "Pop",
"dance rock":        "Rock",
"danish pop":        "Pop",
"danish pop rock":       "Pop" ,
"detroit hip hop":        "Rap/Hip-Hop",
"disco":        "House/Electronic/Trance",
"diva house":        "House/Electronic/Trance",
"downtempo":      "Other"  ,
"dutch americana":       "Folk/Country" ,
"dutch cabaret":       "Other" ,
"dutch hip hop":      "Rap/Hip-Hop"  ,
"dutch indie":        "Rock",
"dutch metal":        "Hard Rock/Metal",
"dutch pop":        "Pop",
"dutch prog":       "Rock" ,
"dutch rock":        "Rock",
"east coast hip hop":     "Rap/Hip-Hop"   ,
"edm":       "House/Electronic/Trance",
"electro":        "House/Electronic/Trance",
"electro house":      "House/Electronic/Trance"  ,
"electronica":      "House/Electronic/Trance"  ,
"electropop":       "House/Electronic/Trance" ,
"eurodance":     "House/Electronic/Trance"    ,
"europop":       "Pop" ,
"finnish metal":     "Hard Rock/Metal"   ,
"folk":        "Folk/Country",
"folk-pop":       "Pop" ,
"funk":        "Soul/Funk",
"g funk":        "Soul/Funk",
"gabba":       "House/Electronic/Trance",
"gangster rap":      "Rap/Hip-Hop"  ,
"garage rock":      "Rock"  ,
"german alternative rock":"Rock"        ,
"german pop":        "Pop",
"german pop rock":       "Pop" ,
"glam metal":        "Hard Rock/Metal",
"glam rock":        "Rock",
"happy hardcore":      "Hard Rock/Metal"  ,
"hard rock":       "Hard Rock/Metal"   ,
"hip pop":      "Pop"  ,
"icelandic indie":  "Rock"      ,
"indie anthem-folk":     "Folk/Country"   ,
"indie pop":        "Pop",
"irish pop":        "Pop",
"irish rock":        "Rock",
"irish singer-songwriter":"Folk/Country"        ,
"italian pop":        "Pop",
"j-core":       "House/Electronic/Trance" ,
"la pop":      "Pop"  ,
"laboratorio":      "Other"  ,
"latin":        "Latin",
"latin alternative":  "Latin"      ,
"latin jazz":        "Jazz",
"levenslied":        "Folk/Country",
"mellow gold":      "Rock"  ,
"metropopolis":      "Pop"  ,
"modern folk rock":      "Rock"  ,
"modern rock":        "Rock",
"motown":       "Soul/Funk" ,
"nederpop":   "Pop"     ,
"neo mellow":     "Rock"   ,
"neo soul":        "Soul/Funk",
"new wave pop":    "Pop"    ,
"operatic pop":        "Pop",
"permanent wave":  "Rock"      ,
"pop":      "Pop"  ,
"pop punk":     "Punk"   ,
"punk":     "Punk"   ,
"reggae":      "House/Electronic/Trance"  ,
"reggae fusion":        "House/Electronic/Trance",
"rock-and-roll":     "Rock & Roll"   ,
"scottish singer-songwriter":        "Folk/Country",
"soft rock":        "Rock",
"stomp and holler":      "Folk/Country"  ,
"streektaal":       "Folk/Country" ,
"trance":        "House/Electronic/Trance",
"uk pop":        "Pop",
"yacht rock":    "Rock"    ,
}

df['Broad Genre'] = df['Top Genre'].str.lower().map(genre_map)

print(df['Broad Genre'].value_counts())

output_path = '../data/Spotify-2000-updated.csv'
df.to_csv(output_path, index=False)